import os
POSTGRES_URL="postgresql+psycopg2://postgres:aman1234@localhost:5432/retail_analytics"
FILE_UPLOAD_DIR=os.path.join(os.getcwd(),'uploaded_files')
SQLALCHEMY_DATABASE_URI='SQLALCHEMY_DATABASE_URI'
MAX_CONTENT_LENGTH='MAX_CONTENT_LENGTH'
SQLALCHEMY_TRACK_MODIFICATIONS='SQLALCHEMY_TRACK_MODIFICATIONS'
FILE_UPLOADS='FILE_UPLOADS'
UPLOAD_FOLDER='UPLOAD_FOLDER'
TABLE_NAME='Product_Details'
SCHEMA={'schema': 'retail'}
OBJECT_ADD_SUCCESS='Object addition to session is successful.'
OBJECT_ADD_FAIL='Object addition to session fails with an error.'
ERROR_MSG="Some error occurred."
FILE_ERROR_MSG="There was an error uploading the file."
DATA_ADD_SUCCESS='Data was added succesfully.'
STORE_ID='store_id'
STORE_ID_TITLE='Store_Id'
PRODUCT_NAME='product_name'
SKU='sku'
PRICE='price'
DATE='date'
ID='id'
INSTANCE_STATE='_sa_instance_state'
HOST='127.0.0.1'
RETAIL_HTML="file_upload_form.html"
ACTION='action'
INNER_FLAG='display'
RECORD_DATA_TEMPLATE='record_data_template'
FLAG_HOME='home'
FLAG_ERROR='error'
NO_RECORD_FOUND_MSG='There are no records to display.'
NO_RECORD_FOUND='no_results'
NO_RECORD_FOUND_FOR_UPDATE='There is no record to undergo update operation.'
NO_RECORD_FOUND_FOR_DELETE='There is no record to undergo delete operation.'